name: Android Kivy Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git zip unzip openjdk-17-jdk             pkg-config libgl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-image-dev             libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev             libavformat-dev libavcodec-dev zlib1g-dev
          pip install buildozer

      - name: Build APK
        run: |
          buildozer init || true
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FaceApp-APK
          path: bin/*.apk
