name: Android Kivy Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------------------------
      # 1. Check out source
      - name: Checkout
        uses: actions/checkout@v4

      # -------------------------------------------------
      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      # -------------------------------------------------
      # 3. Install system + Python deps (now includes ANT)
      - name: Install Buildozer tool‑chain
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git zip unzip openjdk-17-jdk ant \
            pkg-config libgl1-mesa-dev libgles2-mesa-dev \
            libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev \
            zlib1g-dev
          python -m pip install --upgrade pip
          pip install "cython<3.0" buildozer

      # 4. Make ANT visible to Buildozer
      - name: Export ANT env
        run: |
          echo "ANT_HOME=/usr/share/ant" >> "$GITHUB_ENV"
          echo "/usr/share/ant/bin" >> "$GITHUB_PATH"

      # -------------------------------------------------
      # 5. Build APK
      - name: Build APK with Buildozer
        run: |
          buildozer init || true          # creates spec if missing
          buildozer -v android debug      # compile unsigned debug apk

      # -------------------------------------------------
      # 6. Upload artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FaceApp-APK
          path: bin/*.apk
